services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - .puppeteerrc.cjs