services:
  - type: web
    name: message-flow
    env: node
    buildCommand: |
      apt-get update && 
      apt-get install -y chromium-browser && 
      npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - .puppeteerrc.cjs